# Generated by Django 5.2.5 on 2025-09-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienvenida', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
